export interface ExtractedInfo {
  symptoms: string
  occupationalHistory: string
  diagnosis: string
}

export interface LegalProcess {
  id: number
  title: string
  patientName: string
  diseaseType: string
  status: "Pendente" | "Processando" | "Concluído"
  uploadDate: string
  processNumber: string
  extractedInfo?: ExtractedInfo
  reportGenerated: boolean
}

export const mockProcesses: LegalProcess[] = [
  {
    id: 1,
    title: "Processo LER/DORT - Digitador",
    patientName: "Maria Silva Santos",
    diseaseType: "LER/DORT",
    status: "Concluído",
    uploadDate: "15/12/2024",
    processNumber: "1234567-89.2024.5.03.0001",
    extractedInfo: {
      symptoms:
        "Dor crônica nos punhos e dedos, formigamento nas mãos, dificuldade para digitar por períodos prolongados",
      occupationalHistory: "Trabalhou como digitadora por 8 anos sem pausas regulares, com jornada de 9 horas diárias",
      diagnosis: "Síndrome do Túnel do Carpo bilateral, compatível com LER/DORT",
    },
    reportGenerated: true,
  },
  {
    id: 2,
    title: "Processo Perda Auditiva - Operário",
    patientName: "João Pedro Oliveira",
    diseaseType: "Perda Auditiva",
    status: "Processando",
    uploadDate: "14/12/2024",
    processNumber: "2345678-90.2024.5.03.0002",
    extractedInfo: {
      symptoms: "Diminuição progressiva da audição bilateral, zumbido constante",
      occupationalHistory: "Trabalhou 15 anos em ambiente industrial com ruído acima de 85 dB sem proteção adequada",
      diagnosis: "Perda auditiva neurossensorial bilateral induzida por ruído ocupacional",
    },
    reportGenerated: false,
  },
  {
    id: 3,
    title: "Processo Doença Respiratória - Mineiro",
    patientName: "Carlos Eduardo Lima",
    diseaseType: "Doença Respiratória",
    status: "Concluído",
    uploadDate: "13/12/2024",
    processNumber: "3456789-01.2024.5.03.0003",
    extractedInfo: {
      symptoms: "Dispneia aos esforços, tosse crônica produtiva, fadiga",
      occupationalHistory: "Trabalhou 20 anos em mineração com exposição a poeiras minerais",
      diagnosis: "Pneumoconiose (Silicose) grau II",
    },
    reportGenerated: true,
  },
  {
    id: 4,
    title: "Processo Dermatose - Químico",
    patientName: "Ana Paula Costa",
    diseaseType: "Dermatose",
    status: "Pendente",
    uploadDate: "12/12/2024",
    processNumber: "4567890-12.2024.5.03.0004",
    reportGenerated: false,
  },
  {
    id: 5,
    title: "Processo Distúrbio Mental - Bancária",
    patientName: "Fernanda Souza Martins",
    diseaseType: "Distúrbio Mental",
    status: "Processando",
    uploadDate: "11/12/2024",
    processNumber: "5678901-23.2024.5.03.0005",
    extractedInfo: {
      symptoms: "Ansiedade generalizada, insônia, sintomas depressivos, crises de pânico",
      occupationalHistory: "Trabalhou 12 anos em agência bancária com metas abusivas e pressão constante",
      diagnosis: "Transtorno de ansiedade generalizada e síndrome de burnout relacionados ao trabalho",
    },
    reportGenerated: false,
  },
  {
    id: 6,
    title: "Processo LER/DORT - Caixa de Supermercado",
    patientName: "Roberto Alves Pereira",
    diseaseType: "LER/DORT",
    status: "Pendente",
    uploadDate: "10/12/2024",
    processNumber: "6789012-34.2024.5.03.0006",
    reportGenerated: false,
  },
  {
    id: 7,
    title: "Processo Perda Auditiva - DJ",
    patientName: "Lucas Henrique Rocha",
    diseaseType: "Perda Auditiva",
    status: "Concluído",
    uploadDate: "09/12/2024",
    processNumber: "7890123-45.2024.5.03.0007",
    extractedInfo: {
      symptoms: "Perda auditiva bilateral progressiva, zumbido persistente",
      occupationalHistory: "Trabalhou 10 anos como DJ em casas noturnas com exposição prolongada a som alto",
      diagnosis: "Perda auditiva neurossensorial bilateral induzida por ruído",
    },
    reportGenerated: true,
  },
  {
    id: 8,
    title: "Processo Doença Respiratória - Pintor",
    patientName: "Paulo Cesar Menezes",
    diseaseType: "Doença Respiratória",
    status: "Processando",
    uploadDate: "08/12/2024",
    processNumber: "8901234-56.2024.5.03.0008",
    reportGenerated: false,
  },
  {
    id: 9,
    title: "Processo Dermatose - Cabeleireira",
    patientName: "Juliana Ferreira Dias",
    diseaseType: "Dermatose",
    status: "Concluído",
    uploadDate: "07/12/2024",
    processNumber: "9012345-67.2024.5.03.0009",
    extractedInfo: {
      symptoms: "Dermatite de contato nas mãos, ressecamento, fissuras",
      occupationalHistory: "Trabalhou 8 anos como cabeleireira com exposição diária a produtos químicos",
      diagnosis: "Dermatite de contato ocupacional por sensibilização a produtos químicos",
    },
    reportGenerated: true,
  },
  {
    id: 10,
    title: "Processo Distúrbio Mental - Enfermeira",
    patientName: "Mariana Santos Silva",
    diseaseType: "Distúrbio Mental",
    status: "Pendente",
    uploadDate: "06/12/2024",
    processNumber: "0123456-78.2024.5.03.0010",
    reportGenerated: false,
  },
  {
    id: 11,
    title: "Processo LER/DORT - Costureira",
    patientName: "Beatriz Almeida Cruz",
    diseaseType: "LER/DORT",
    status: "Processando",
    uploadDate: "05/12/2024",
    processNumber: "1234567-89.2024.5.03.0011",
    extractedInfo: {
      symptoms: "Dor nos ombros e pescoço, tendinite nos punhos",
      occupationalHistory: "Trabalhou 12 anos em confecção com movimentos repetitivos",
      diagnosis: "Tendinite bilateral e síndrome do impacto do ombro relacionadas ao trabalho",
    },
    reportGenerated: false,
  },
  {
    id: 12,
    title: "Processo Perda Auditiva - Mecânico",
    patientName: "Ricardo Souza Barbosa",
    diseaseType: "Perda Auditiva",
    status: "Concluído",
    uploadDate: "04/12/2024",
    processNumber: "2345678-90.2024.5.03.0012",
    extractedInfo: {
      symptoms: "Dificuldade para ouvir conversas, necessidade de aumentar volume da TV",
      occupationalHistory: "Trabalhou 18 anos em oficina mecânica com exposição a ruído de ferramentas",
      diagnosis: "Perda auditiva bilateral relacionada ao trabalho",
    },
    reportGenerated: true,
  },
  {
    id: 13,
    title: "Processo Doença Respiratória - Soldador",
    patientName: "André Luiz Carvalho",
    diseaseType: "Doença Respiratória",
    status: "Pendente",
    uploadDate: "03/12/2024",
    processNumber: "3456789-01.2024.5.03.0013",
    reportGenerated: false,
  },
  {
    id: 14,
    title: "Processo Dermatose - Faxineira",
    patientName: "Sandra Regina Pinto",
    diseaseType: "Dermatose",
    status: "Processando",
    uploadDate: "02/12/2024",
    processNumber: "4567890-12.2024.5.03.0014",
    extractedInfo: {
      symptoms: "Eczema nas mãos, coceira intensa, descamação",
      occupationalHistory: "Trabalhou 10 anos com produtos de limpeza sem proteção adequada",
      diagnosis: "Dermatite de contato irritativa por exposição ocupacional",
    },
    reportGenerated: false,
  },
  {
    id: 15,
    title: "Processo Distúrbio Mental - Motorista",
    patientName: "Marcos Antonio Gomes",
    diseaseType: "Distúrbio Mental",
    status: "Concluído",
    uploadDate: "01/12/2024",
    processNumber: "5678901-23.2024.5.03.0015",
    extractedInfo: {
      symptoms: "Estresse crônico, irritabilidade, insônia",
      occupationalHistory: "Trabalhou 15 anos como motorista de ônibus com jornadas extensas",
      diagnosis: "Transtorno de adaptação com ansiedade relacionado ao estresse ocupacional",
    },
    reportGenerated: true,
  },
  {
    id: 16,
    title: "Processo LER/DORT - Empacotador",
    patientName: "Claudio Henrique Ribeiro",
    diseaseType: "LER/DORT",
    status: "Pendente",
    uploadDate: "30/11/2024",
    processNumber: "6789012-34.2024.5.03.0016",
    reportGenerated: false,
  },
  {
    id: 17,
    title: "Processo Perda Auditiva - Músico",
    patientName: "Rafael Santos Moreira",
    diseaseType: "Perda Auditiva",
    status: "Processando",
    uploadDate: "29/11/2024",
    processNumber: "7890123-45.2024.5.03.0017",
    reportGenerated: false,
  },
  {
    id: 18,
    title: "Processo Doença Respiratória - Carpinteiro",
    patientName: "Sergio Luiz Campos",
    diseaseType: "Doença Respiratória",
    status: "Concluído",
    uploadDate: "28/11/2024",
    processNumber: "8901234-56.2024.5.03.0018",
    extractedInfo: {
      symptoms: "Tosse crônica, dispneia, chiado no peito",
      occupationalHistory: "Trabalhou 22 anos em carpintaria com exposição a poeira de madeira",
      diagnosis: "Asma ocupacional por inalação de poeira de madeira",
    },
    reportGenerated: true,
  },
  {
    id: 19,
    title: "Processo Dermatose - Jardineiro",
    patientName: "Wagner Silva Nunes",
    diseaseType: "Dermatose",
    status: "Pendente",
    uploadDate: "27/11/2024",
    processNumber: "9012345-67.2024.5.03.0019",
    reportGenerated: false,
  },
  {
    id: 20,
    title: "Processo Distúrbio Mental - Teleoperador",
    patientName: "Patricia Costa Lima",
    diseaseType: "Distúrbio Mental",
    status: "Processando",
    uploadDate: "26/11/2024",
    processNumber: "0123456-78.2024.5.03.0020",
    extractedInfo: {
      symptoms: "Ansiedade, sintomas depressivos, dores de cabeça frequentes",
      occupationalHistory: "Trabalhou 7 anos em call center com metas abusivas e monitoramento constante",
      diagnosis: "Transtorno misto ansioso-depressivo relacionado ao trabalho",
    },
    reportGenerated: false,
  },
]
